services:
  db:
    image: postgres:17
    container_name: warehouse-db2
    restart: unless-stopped
    environment:
      POSTGRES_DB: warehouse2
      POSTGRES_USER: warehouse2
      POSTGRES_PASSWORD: warehouse2
    ports:
      - "5433:5432"
    volumes:
      - warehouse_postgres_data2:/var/lib/postgresql/data

volumes:
  warehouse_postgres_data2: